import { Article, Product } from './types';

export const GLOSSIER_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Boy Brow',
    brand: 'Turpeen Cosmetics',
    price: 18,
    rating: 4.8,
    description: 'Our award-winning brushable eyebrow pomade that visibly thickens, shapes, and grooms brows into place.',
    image: 'https://images.unsplash.com/photo-1625093742435-6fa192b6fb10?auto=format&fit=crop&w=400&q=80',
    category: 'makeup',
  },
  {
    id: 'p2',
    name: 'Balm Dotcom',
    brand: 'Turpeen Cosmetics',
    price: 14,
    rating: 4.9,
    description: 'A hydrating lip balm and skin salve packed with antioxidants and natural emollients to nourish dry, chafed skin.',
    image: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=400&q=80',
    category: 'skincare',
  },
  {
    id: 'p3',
    name: 'Milky Jelly Cleanser',
    brand: 'Turpeen Cosmetics',
    price: 19,
    rating: 4.7,
    description: 'A gentle face wash with a pH-balanced, creamy gel formula made with poloxamer (a safe cleaning agent found in contact lens solution).',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80',
    category: 'skincare',
  },
  {
    id: 'p4',
    name: 'Turpeen You',
    brand: 'Turpeen Cosmetics',
    price: 68,
    rating: 4.9,
    description: 'The ultimate personal fragrance. Formulated to smell like you, but better. Soft, warm, and familiar with sparkling notes of pink pepper and iris.',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=400&q=80',
    category: 'fragrance',
  },
  {
    id: 'p5',
    name: 'Cloud Paint',
    brand: 'Turpeen Cosmetics',
    price: 20,
    rating: 4.8,
    description: 'A seamless, buildable gel-cream blush that is fun to apply, easy to wear, and delivers a healthy, natural-looking flush.',
    image: 'https://images.unsplash.com/photo-1631730359575-38e4755d772b?auto=format&fit=crop&w=400&q=80',
    category: 'makeup',
  },
  {
    id: 'p6',
    name: 'Futuredew',
    brand: 'Turpeen Cosmetics',
    price: 26,
    rating: 4.6,
    description: 'An oil-serum hybrid that slips easily onto skin, giving you an instant shortcut to that dewy, fresh-from-the-facial glow.',
    image: 'https://images.unsplash.com/photo-1608248597481-496100c80836?auto=format&fit=crop&w=400&q=80',
    category: 'skincare',
  },
];

export const ARTICLES: Article[] = [];

export const TOP_25_BRANDS = [
  {
    rank: 1,
    name: 'O.Piccola',
    category: 'Clean Makeup',
    tagline: 'Minimalist, foolproof formulas for modern dewy skin.',
    heroProduct: 'Piccola Lip Dew Oil',
    founded: '2025',
  },
  {
    rank: 2,
    name: 'Soft Services',
    category: 'Body Care',
    tagline: 'Highly targeted skin solutions for below-the-neck concerns.',
    heroProduct: 'Buffing Bar',
    founded: '2021',
  },
  {
    rank: 3,
    name: 'Kulfi Beauty',
    category: 'Color Cosmetics',
    tagline: 'Vibrant, high-pigment liners celebrating South Asian culture.',
    heroProduct: 'Underlined Kajal',
    founded: '2020',
  },
  {
    rank: 4,
    name: 'Dieux Skin',
    category: 'Skincare Actives',
    tagline: 'Transparently priced clinical actives with maximum efficacy.',
    heroProduct: 'Deliverance Serum',
    founded: '2020',
  },
  {
    rank: 5,
    name: 'Crown Affair',
    category: 'Hair Wellness',
    tagline: 'A ritual-based system of hair brushes, oils, and silk accessories.',
    heroProduct: 'The Oil',
    founded: '2019',
  },
];
