import { Article, Product } from './types';

export const GLOSSIER_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Boy Brow',
    brand: 'Turpeen Cosmetics',
    price: 18,
    rating: 4.8,
    description: 'Our award-winning brushable eyebrow pomade that visibly thickens, shapes, and grooms brows into place.',
    image: 'https://images.unsplash.com/photo-1625093742435-6fa192b6fb10?auto=format&fit=crop&w=400&q=80',
    category: 'makeup',
  },
  {
    id: 'p2',
    name: 'Balm Dotcom',
    brand: 'Turpeen Cosmetics',
    price: 14,
    rating: 4.9,
    description: 'A hydrating lip balm and skin salve packed with antioxidants and natural emollients to nourish dry, chafed skin.',
    image: 'https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=400&q=80',
    category: 'skincare',
  },
  {
    id: 'p3',
    name: 'Milky Jelly Cleanser',
    brand: 'Turpeen Cosmetics',
    price: 19,
    rating: 4.7,
    description: 'A gentle face wash with a pH-balanced, creamy gel formula made with poloxamer (a safe cleaning agent found in contact lens solution).',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80',
    category: 'skincare',
  },
  {
    id: 'p4',
    name: 'Turpeen You',
    brand: 'Turpeen Cosmetics',
    price: 68,
    rating: 4.9,
    description: 'The ultimate personal fragrance. Formulated to smell like you, but better. Soft, warm, and familiar with sparkling notes of pink pepper and iris.',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=400&q=80',
    category: 'fragrance',
  },
  {
    id: 'p5',
    name: 'Cloud Paint',
    brand: 'Turpeen Cosmetics',
    price: 20,
    rating: 4.8,
    description: 'A seamless, buildable gel-cream blush that is fun to apply, easy to wear, and delivers a healthy, natural-looking flush.',
    image: 'https://images.unsplash.com/photo-1631730359575-38e4755d772b?auto=format&fit=crop&w=400&q=80',
    category: 'makeup',
  },
  {
    id: 'p6',
    name: 'Futuredew',
    brand: 'Turpeen Cosmetics',
    price: 26,
    rating: 4.6,
    description: 'An oil-serum hybrid that slips easily onto skin, giving you an instant shortcut to that dewy, fresh-from-the-facial glow.',
    image: 'https://images.unsplash.com/photo-1608248597481-496100c80836?auto=format&fit=crop&w=400&q=80',
    category: 'skincare',
  },
];

export const ARTICLES: Article[] = [
  {
    id: 'art-1',
    title: 'Olivia Jade Giannulli, Founder, O.Piccola',
    subtitle: 'The beauty entrepreneur on natural highlights, simple hydration, and the art of looking awake.',
    slug: 'olivia-jade-giannulli',
    category: 'Interviews',
    badge: 'THE TOP SHELF',
    author: 'Emily Ferber',
    authorTitle: 'Founder, O.Piccola',
    date: 'July 8, 2026',
    readTime: '6 min read',
    excerpt: 'The beauty entrepreneur talks natural highlights, simple hydration, and the exact routine that got her through launching O.Piccola.',
    images: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1515688594390-b649af70d282?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1608248597481-496100c80836?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1522335936273-755e37f4063d?auto=format&fit=crop&w=400&q=80',
    ],
    isHero: true,
    blocks: [
      {
        type: 'paragraph',
        text: '“I have always loved beauty, but launching O.Piccola changed everything. You transition from someone who just consumes skincare to someone who has to deeply care about what is inside the jar, how it stabilizes, and how it behaves on the skin in the middle of a hot summer day.”',
      },
      {
        type: 'heading',
        text: 'The Morning Ritual',
      },
      {
        type: 'paragraph',
        text: 'I keep things incredibly simple because my skin gets congested easily if I use too many layers. In the morning, I don’t even use a traditional cleanser—just lukewarm water and a muslin cloth. It keeps my natural moisture barrier intact, which is half the battle when you live in a dry climate.',
      },
      {
        type: 'product-highlight',
        productName: 'Milky Jelly Cleanser',
        productBrand: 'Turpeen Cosmetics',
        productDesc: '“If I had a late night or wore heavy SPF the day before, I do reach for this. It smells subtle, never strips my skin, and leaves that bouncy texture I crave.”',
      },
      {
        type: 'paragraph',
        text: 'For makeup, it’s all about the illusion of sleep. I’m a big fan of dynamic, dewy bases. I mix my foundation with a drop of facial oil or a hydrating primer. If my skin looks dry, I feel like I look tired. There’s something about a slight sheen on the high points of your face that screams ‘I drank three liters of water and slept nine hours,’ even if the reality is far from it.',
      },
      {
        type: 'quote',
        authorQuote: 'Olivia Jade Giannulli',
        text: '“Skincare shouldn’t feel like homework. If it doesn’t bring you joy in the morning, change the routine. It’s the five minutes of the day that are completely yours.”',
      },
      {
        type: 'heading',
        text: 'The O.Piccola Philosophy',
      },
      {
        type: 'paragraph',
        text: 'When we designed our first product line, we wanted things that didn’t require a mirror to apply. I want a lip oil I can swipe on while walking to get coffee. I want a cream highlight that is foolproof. If you need a specialized brush and perfect lighting, it doesn’t belong in my bag anymore. We’re moving toward ease, simplicity, and a returned focus on healthy, bare skin.',
      },
    ],
  },
  {
    id: 'art-2',
    title: "Inside A Dermatologist's Beauty Routine",
    subtitle: 'With Dr. Shereene Idriss',
    slug: 'inside-dermatologist-beauty-routine',
    category: 'Skincare',
    badge: 'THE TOP SHELF',
    author: 'Ali Oshinsky',
    authorTitle: 'Dermatologist',
    date: 'July 10, 2026',
    readTime: '4 min read',
    excerpt: 'Dr. Shereene Idriss breaks down her clinical-meets-cosmetic approach to skincare, active ingredients, and the sunscreen rules she never breaks.',
    images: [
      'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1608248597481-496100c80836?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=400&q=80',
    ],
    isSecondaryHero: true,
    blocks: [
      {
        type: 'paragraph',
        text: '“People assume dermatologists have a 15-step medical-grade routine that smells like a pharmacy. In reality, we are just as susceptible to wanting a beautiful sensory experience as anyone else. The difference is we look strictly at active percentages and molecular weights.”',
      },
      {
        type: 'heading',
        text: 'Actives That Actually Work',
      },
      {
        type: 'paragraph',
        text: 'If you have hyperpigmentation, stop buying twenty different serums. Pick one solid Vitamin C for the morning, and a retinol or glycolic acid for the night. The skin can only process so much before it triggers an inflammatory response. Inflammation is the enemy of glowing skin.',
      },
      {
        type: 'product-highlight',
        productName: 'Futuredew Oil-Serum Hybrid',
        productBrand: 'Turpeen Cosmetics',
        productDesc: '“I use this as the final step in my morning routine, right over my sunscreen. It acts as a sealer that keeps moisture from evaporating throughout the day while catching light beautifully.”',
      },
      {
        type: 'quote',
        authorQuote: 'Dr. Shereene Idriss',
        text: '“Sunscreen is non-negotiable. If you aren’t wearing it daily, you might as well throw your expensive anti-aging serums down the drain.”',
      },
    ],
  },
  {
    id: 'art-3',
    title: 'The Celebrity Colorist Whose Trickiest Client Is Herself',
    subtitle: 'How Emaly Baum manages hair care and alopecia.',
    slug: 'celebrity-colorist-emaly-baum',
    category: 'Hair',
    badge: 'POSTCARD',
    author: 'Ashley Weatherford',
    date: 'July 5, 2026',
    readTime: '5 min read',
    excerpt: 'How Emaly Baum manages her alopecia inbetween appointments with Anna Van Patten, Molly Young, and more.',
    images: [
      'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1582095133179-bfd08e2fc6b3?auto=format&fit=crop&w=400&q=80',
    ],
    isLatest: true,
    blocks: [
      {
        type: 'paragraph',
        text: 'As a hair colorist to some of the most visible faces in New York, Emaly Baum is used to dealing with high stakes. But her personal hair journey has been one of vulnerability, learning to adapt, and embracing changing hair densities.',
      },
      {
        type: 'heading',
        text: 'The Art of Hair Health',
      },
      {
        type: 'paragraph',
        text: '“When you suffer from alopecia, your relationship with your hair changes from aesthetic to biological. You stop asking ‘How blonde can I go?’ and start asking ‘How can I feed my hair follicles?’ I had to re-examine my entire line of styling agents.”',
      },
      {
        type: 'quote',
        authorQuote: 'Emaly Baum',
        text: '“Sometimes the most radical thing you can do for your hair is absolutely nothing. Let it air dry, put down the curling iron, and focus on scalp circulation instead.”',
      },
    ],
  },
  {
    id: 'art-4',
    title: 'Daniela Garza, Director',
    subtitle: 'The filmmaker on continental color palettes and travel beauty hacks.',
    slug: 'daniela-garza',
    category: 'Interviews',
    badge: 'THE FACE',
    author: 'Chloe Hall',
    authorTitle: 'Director',
    date: 'July 3, 2026',
    readTime: '7 min read',
    excerpt: "The director—better known as @mexicanfaerie—curates her color palette to the continent she's visiting.",
    images: [
      'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1515688594390-b649af70d282?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=400&q=80',
    ],
    isLatest: true,
    blocks: [
      {
        type: 'paragraph',
        text: '“I treat my face like a film frame. Every color choice—whether it is a deep terracotta lipstick or a highly specific lilac eyeshadow—needs to harmonize with the local architecture, the quality of the light, and the general mood of the city I am shooting in.”',
      },
      {
        type: 'heading',
        text: 'Curating the Color Palette',
      },
      {
        type: 'paragraph',
        text: 'When I’m in Europe, the lighting is very cool and overcast, so I lean into desaturated, classic tones—maybe a soft berry stain on the lips. But when I am back in Mexico City, the sun is high and vivid. I want warm corals, golden highlights, and skin that feels alive and glossy.',
      },
      {
        type: 'product-highlight',
        productName: 'Cloud Paint in Beam',
        productBrand: 'Turpeen Cosmetics',
        productDesc: '“This is the most cinematic peach blush ever created. It blends instantly with my fingers and looks like an authentic sun flush under any camera lens.”',
      },
    ],
  },
  {
    id: 'art-5',
    title: 'Emily Henry, Author',
    subtitle: 'The bestselling novelist on fourth grade ambitions, setting-inspired conflicts, and writing life stories.',
    slug: 'emily-henry-author',
    category: 'Interviews',
    badge: 'THE FACE',
    author: 'Emily Henry',
    authorTitle: 'Author',
    date: 'July 1, 2026',
    readTime: '8 min read',
    excerpt: '“When I was in fourth grade, there was an assignment where I needed to write my autobiography in the future tense...”',
    images: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=400&q=80',
      'https://images.unsplash.com/photo-1522335936273-755e37f4063d?auto=format&fit=crop&w=400&q=80',
    ],
    isLatest: true,
    blocks: [
      {
        type: 'paragraph',
        text: '“When I was in fourth grade, there was an assignment where I needed to write my autobiography in the future tense. One of the things we had to consider was what we’d do when we were older. That was when it occurred to me that someone was actually writing the books I loved. So I started writing my own stories because I realized I could do it, too. From that point forward, I was like, That’s it. That’s the job.”',
      },
      {
        type: 'paragraph',
        text: 'I’ve written 10 books of my own now. Great Big Beautiful Life, my last release, follows two journalists competing for the chance to tell the life story of an heiress who vanished from the spotlight 20 years earlier. She’s a media heiress—think a Hearst or a Murdoch—born into extreme wealth and privilege but marked by her own trials and tribulations. Nobody really knows what happened to her. Over the course of the month that these two journalists are vying for her trust, they start to realize she’s telling them different stories and they have to get to the bottom of it.',
      },
      {
        type: 'paragraph',
        text: 'My books are usually inspired by a few settings. There’s often a setting I’m excited about—in this case, a small Georgian island draped in Spanish moss and live oak, an atmosphere that feels a little haunted and steeped in history. I also knew I wanted to write two characters who had external factors keeping them apart, since I usually explore more internal ones. My book before that, Funny Story, was about two people who were really nice and genuinely liked each other, which was shockingly hard to turn into a story because you need conflict. I wanted that conflict baked in.',
      },
    ],
  },

  // SIDEBAR & DON'T MISS ARTICLES
  {
    id: 'sid-1',
    title: 'How To Be A Person Who Has Their Life Together',
    slug: 'how-to-have-life-together',
    category: 'Skincare',
    badge: 'THE REVIEW',
    author: 'Turpeen Editors',
    date: 'June 28, 2026',
    readTime: '3 min read',
    excerpt: 'An investigative report into those girls who organize their medicine cabinets alphabetically.',
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=400&q=80'],
    isSidebar: true,
    sidebarBadge: 'THE EXTRAS',
    blocks: [
      {
        type: 'paragraph',
        text: 'It starts with matching towels, moves to structured planners, and ends with a immaculate routine that feels entirely unbothered by the daily chaos of the city.',
      },
    ],
  },
  {
    id: 'sid-2',
    title: "What's Everyone Reading? Summer Book Club",
    slug: 'whats-everyone-reading',
    category: 'Interviews',
    badge: 'OPEN THREAD',
    author: 'Turpeen Community',
    date: 'June 25, 2026',
    readTime: '10 min read',
    excerpt: 'Tell us what is currently on your nightstand, beach bag, or iPad. We want recommendations!',
    images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=400&q=80'],
    isSidebar: true,
    sidebarBadge: 'OPEN THREAD',
    blocks: [
      {
        type: 'paragraph',
        text: 'From indie fiction to dense scientific studies on hair health, tell us what you’re currently reading and what products you’re pairing with your reading sessions.',
      },
    ],
  },
  {
    id: 'sid-3',
    title: "For Every Top Shelf, There's a Bottom Shelf",
    slug: 'every-top-shelf-bottom-shelf',
    category: 'Makeup',
    badge: 'THE REVIEW',
    author: 'Molly Young',
    date: 'June 20, 2026',
    readTime: '4 min read',
    excerpt: 'We explore the hidden, cluttered cabinet drawers where the expired sheet masks and impulse buys live.',
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=400&q=80'],
    isSidebar: true,
    sidebarBadge: 'THE REVIEW',
    blocks: [
      {
        type: 'paragraph',
        text: 'We always talk about the perfect, curated top shelves. But what about the bottom shelves? The half-used tubes, the weird clay masks, the beauty tools we used exactly once.',
      },
    ],
  },
  {
    id: 'sid-4',
    title: 'How Not To Mess Up Your At-Home Hair Color',
    slug: 'how-to-at-home-hair-color',
    category: 'Hair',
    badge: 'GUIDE',
    author: 'Emaly Baum',
    date: 'June 15, 2026',
    readTime: '5 min read',
    excerpt: 'Three rules from a professional colorist before you buy that box dye at the pharmacy.',
    images: ['https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=400&q=80'],
    isSidebar: true,
    sidebarBadge: 'GUIDE',
    blocks: [
      {
        type: 'paragraph',
        text: 'First: don’t panic. Second: don’t try to go more than two shades lighter or darker than your current state. Third: read our breakdown of skin-tone compatibility.',
      },
    ],
  },
  {
    id: 'sid-5',
    title: 'The Makeup Bags Of Turpeen HQ: Extreme Makeover Edition',
    slug: 'makeup-bags-turpeen-hq',
    category: 'Makeup',
    badge: 'THE EXTRAS',
    author: 'Ali Oshinsky',
    date: 'June 10, 2026',
    readTime: '6 min read',
    excerpt: 'We dumped the contents of ten employees’ makeup pouches to see what they actually use.',
    images: ['https://images.unsplash.com/photo-1522335936273-755e37f4063d?auto=format&fit=crop&w=400&q=80'],
    isSidebar: true,
    sidebarBadge: 'THE EXTRAS',
    blocks: [
      {
        type: 'paragraph',
        text: 'It turns out that working at Turpeen Cosmetics doesn’t protect you from having five separate lip liners that are almost identical in color. See our visual breakdown.',
      },
    ],
  },
  {
    id: 'sid-6',
    title: 'Find Your Tinted Moisturizer Soulmate',
    slug: 'tinted-moisturizer-soulmate',
    category: 'Makeup',
    badge: 'GUIDE',
    author: 'Turpeen Editors',
    date: 'June 05, 2026',
    readTime: '4 min read',
    excerpt: 'A comprehensive chart to pair your skin type, hydration needs, and preferred finish with the perfect tint.',
    images: ['https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=400&q=80'],
    isSidebar: true,
    sidebarBadge: 'GUIDE',
    blocks: [
      {
        type: 'paragraph',
        text: 'Whether you want a ultra-matte look that holds up in humidity, or a super-dewy cream that doubles as a moisturizer, we’ve found the perfect matches.',
      },
    ],
  },
];

export const TOP_25_BRANDS = [
  {
    rank: 1,
    name: 'O.Piccola',
    category: 'Clean Makeup',
    tagline: 'Minimalist, foolproof formulas for modern dewy skin.',
    heroProduct: 'Piccola Lip Dew Oil',
    founded: '2025',
  },
  {
    rank: 2,
    name: 'Soft Services',
    category: 'Body Care',
    tagline: 'Highly targeted skin solutions for below-the-neck concerns.',
    heroProduct: 'Buffing Bar',
    founded: '2021',
  },
  {
    rank: 3,
    name: 'Kulfi Beauty',
    category: 'Color Cosmetics',
    tagline: 'Vibrant, high-pigment liners celebrating South Asian culture.',
    heroProduct: 'Underlined Kajal',
    founded: '2020',
  },
  {
    rank: 4,
    name: 'Dieux Skin',
    category: 'Skincare Actives',
    tagline: 'Transparently priced clinical actives with maximum efficacy.',
    heroProduct: 'Deliverance Serum',
    founded: '2020',
  },
  {
    rank: 5,
    name: 'Crown Affair',
    category: 'Hair Wellness',
    tagline: 'A ritual-based system of hair brushes, oils, and silk accessories.',
    heroProduct: 'The Oil',
    founded: '2019',
  },
];
